version: "3.8"

services:
  llm_connector:
    build: ../llm_connector
    ports:
      - "8001:8000"
    restart: always

  gradio_frontend:
    build: ../gradio_frontend
    ports:
      - "7860:7860"
    restart: always

